---
spring:
  application:
    name: API-CDT-CDM-SERVICE
  main:
    allow-bean-definition-overriding: true
---
server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    session:
      cookie:
        http-only: true
# 1 days = 1 * 24 * 60 * 60
cookie:
  maxAge: 86400

management:
  server:
    port: 7180
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false

spring:
  config:
    use-legacy-processing: true
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000
  main:
    lazy-initialization: true
  flyway:
    enabled: false

  zipkin:
    enabled: false

feign:
  hystrix:
    enabled: false

keycloak:
  enabled: false

feign-client:
  api-cdm-core-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-master-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-trx-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-master-command-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-trx-command-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-master-query-service.base-url: http://api-cdm-core-service:8080
  api-cdm-core-trx-query-service.base-url: http://api-cdm-core-service:8080
