---
# JVM memory settings
jvm:
  initial-heap-size: 256m
  max-heap-size: 512m

---
spring:
  application:
    name: api-cdt-cdm-service
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  thread-executor: virtual
---
server:
  port: 8080
  error:
    include-stacktrace: never
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
# 1 days = 1 * 24 * 60 * 60
cookie:
  maxAge: 86400

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: WARN
    agus.ramdan.base.exception: DEBUG
    agus.ramdan.cdt.cdm: INFO

management:
  server:
    port: 7180
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false
  metrics:
    tags:
      application: api-cdt-cdm-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: api-cdt-cdm-service

spring:
  config:
    use-legacy-processing: true
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000
  main:
    lazy-initialization: true
  flyway:
    enabled: false

feign:
  hystrix:
    enabled: false

feign-client:
  api-cdt-core-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-master-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-trx-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-master-command-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-trx-command-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-master-query-service.base-url: http://api-cdt-core-service:8080
  api-cdt-core-trx-query-service.base-url: http://api-cdt-core-service:8080
